
plugins {
alias(libs.plugins.android.application) apply false
    alias(libs.plugins.jetbrains.kotlin.android) apply false
    alias(libs.plugins.android.library) apply false
}

ext {
    compileSdkVersion = 35
    targetSdkVersion = 30    // Android 11 target

    minSdk = 30              // Android 11 minimum
    versionCode = 400
    versionName = "4.0.0"
    xVersion = '1.1.0'
    hiddenApiBypass = '4.3'
}
